
services:
  documentation:
    image: squidfunk/mkdocs-material:latest
    container_name: mkdocs_junior
    command: serve --dev-addr=0.0.0.0:8011 --watch-theme
    restart: unless-stopped
    ports:
      - "8100:8011"
    volumes:
      - ./documentation:/docs:ro

  local_database_course:
    image: postgres:16-alpine
    container_name: local_database_course
    hostname: local_database_course
    restart: always
    env_file:
      - .env
    ports:
      - "8787:${POSTGRES_PORT}"
    volumes:
      - postgres_datastorage_course:/var/lib/postgresgl/data
    networks:
      - main_network

  backend_api_course:
    build:
      dockerfile: Dockerfile
      context: ./backend_api
    container_name: backend_api_course
    hostname: backend_api_course
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend_api/app:/app
    ports:
      - "9999:9999"
    command: |
      sh -c "
      alembic upgrade head && \
      uvicorn main:app --port=9999 --host=0.0.0.0 --reload
      "
    networks:
      - main_network

networks:
  main_network:
    driver: bridge

volumes:
  postgres_datastorage_course:
    external: false